server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eucomida
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

